name: Build and Publish amd64-java11-mandrel21.3.0.0

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image to Docker registry
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          build-args: |
            JAVA_VER=java11
            MANDREL_VER=21.3.0.0
            ARCH=amd64
          platforms: linux/amd64
          tags: |
            zapp88/mandrel-multiarch:amd64-java11-mandrel21.3.0.0
