name: Publish latest java 17 manifest

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull images
        run: |
          docker pull zapp88/mandrel-multiarch:amd64-java17-mandrel21.3.0.0
          docker pull zapp88/mandrel-multiarch:arm64-java17-mandrel21.3.0.0
      - name: Amend manifest base
        run: |
          docker manifest create zapp88/mandrel-multiarch:java17-mandrel21.3.0.0 --amend zapp88/mandrel-multiarch:amd64-java17-mandrel21.3.0.0 --amend zapp88/mandrel-multiarch:arm64-java17-mandrel21.3.0.0
          docker manifest push zapp88/mandrel-multiarch:java17-mandrel21.3.0.0
      - name: Amend manifest latest
        run: |
          docker manifest create zapp88/mandrel-multiarch:java17-latest --amend zapp88/mandrel-multiarch:amd64-java17-mandrel21.3.0.0 --amend zapp88/mandrel-multiarch:arm64-java17-mandrel21.3.0.0
          docker manifest push zapp88/mandrel-multiarch:java17-latest
